version: '3.4'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8002:8002
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/
    working_dir: /var/www
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/
    links:
      - db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    ports:
      - "3389:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: application
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: mysql

volumes:
  dbdata:
