import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from "react"
import { createUserApi } from '@/services/API.services'
import { toast } from 'react-toastify';
import { useRouter } from "next/router"

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
    const router = useRouter()
    const [processing, setProcessing] = useState(false);
    const [email, setEmail] = useState("")
    const [first_name, setFirstName] = useState("")
    const [last_name, setLastName] = useState("")

    const handleCreateUser = async (event) => {
        event.preventDefault();
        let data = {email, first_name, last_name}
        try {
            const res = await createUserApi(data)
            if (res.status) {
                toast.success(res.message)
                router.push('/users')
            }
        } catch (e) {
            toast.error(e.message)
        }
    }

    const restForm = (event) => {
        event.preventDefault();
        setFirstName("")
        setLastName("")
        setEmail("")
    }

  return (
    <>
        <Head>
            <title>Create user</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container">
            <h2>Create User</h2>
            <div className="create-user">
                <form onSubmit={handleCreateUser} className="row g-3">
                    <div className="col-md-6">
                        <label className="form-label">First Name</label>
                        <input
                            type="text"
                            className="form-control"
                            placeholder="First name"
                            value={first_name}
                            onChange={event => setFirstName(event.target.value)}
                        />
                    </div>
                    <div className="col-6">
                        <label className="form-label">Last Name</label>
                        <input 
                            type="text"
                            className="form-control"
                            placeholder="Last name"
                            value={last_name}
                            onChange={event => setLastName(event.target.value)}
                        />
                    </div>
                    <div className="col-md-6">
                        <label className="form-label">Email</label>
                        <input 
                            type="email" 
                            className="form-control"
                            value={email}
                            placeholder="Email"
                            onChange={event => setEmail(event.target.value)}
                        />
                    </div>

                    <div>
                        <button onClick={restForm} className="btn btn-secondary" variant="secondary">Reset</button>
                        <button className="btn btn-primary ms-2" type="submit" variant="primary">Save</button>
                    </div>
                </form>
            </div>
        </main>
    </>
  )
}
