import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useEffect, useState } from "react"
import { getUserApi } from '@/services/API.services'
import { toast } from 'react-toastify';
import { useRouter } from "next/router"
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {
    const router = useRouter()
    const [user, setUser] = useState([])
    const userStatus = {1: 'Active', 2: 'Suspended', 3: 'Deleted'};
    
    useEffect(() => {
        const { id } = router.query
        if (id) {
            getUser(id)
        }
    }, [router.query])

    const getUser = async (id) => {
        try {
            const res = await getUserApi(id)
            setUser(res.data)
        } catch (e) {
            toast.error(e.message)
        }
    }

  return (
    <>
        <Head>
            <title>Show user</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container">
            <h2>Show User</h2>
            <div className="show-user">
                <div className="row">
                    <label className="form-label col-md-4">First Name</label>
                    <div className="col-md-8">{user.first_name}</div>
                </div>
                <div className="row">
                    <label className="form-label col-md-4">Last Name</label>
                    <div className="col-md-8">{user.last_name}</div>
                </div>
                <div className="row">
                    <label className="form-label col-md-4">Email</label>
                    <div className="col-md-8">{user.email}</div>
                </div>
                <div className="row">
                    <label className="form-label col-md-4">Status</label>
                    <div className="col-md-8">{userStatus[user.status]}</div>
                </div>

                <div>
                    <Link href="/users">
                        <button className="btn btn-secondary" variant="secondary">Back</button>
                    </Link>
                </div>
            </div>
        </main>
    </>
  )
}
